const SET_ISOPEN = "SE_ISOPEN";
const SET_ACTIVEDATA = "SET_ACTIVEDATA";
const SET_ISOPENINDEX = "SET_ISOPENINDEX";
const SET_EMAIL = "SET_EMAIL";
const SET_ERROR = "SET_ERROR";

export { SET_ISOPEN ,SET_ACTIVEDATA, SET_ISOPENINDEX, SET_EMAIL, SET_ERROR };